### ISSUE TITLE
New update, HdLethalCompany Incompatible

### ISSUE THREAD

**Issue by DigitalIver** [niceh26/Symbiosis#1]
This new Update make Hdlethalcompany not working, i have to check every mod to find the cause and it this one

**Comment by niceh26** [comment]
Are you sure it wasn't diversity? Since they had HdLethalCompany issues the last couple of days

**Comment by IverDigital** [comment]
nope

**Comment by IverDigital** [comment]
i had it on and it work normal

**Comment by niceh26** [comment]
Ok, i will check

**Comment by niceh26** [comment]
What seems to be the problem? I have not encountered any issues.

**Comment by IverDigital** [comment]
the hd lethal company config doesn't work

**Comment by IverDigital** [comment]
with this mod on or the nuclear lib

**Comment by niceh26** [comment]
works for me

**Comment by IverDigital** [comment]
hmm let me check with only nuclear lib on

**Comment by IverDigital** [comment]
uh oops my bad it not the mod cause the issue it must be something else sorry

**Comment by IverDigital** [comment]
well that weird
